### PR TITLE
Mermaid for the architecture diagram

### PR DESCRIPTION
**Pull request by jonathonherbert**
## What does this change?

Adds a mermaid diagram in place of the PNG, and makes a few minor corrections to the README.md

## How to test

Anything to improve the diagram?

### CODE REVIEW

**Comment by andrew-nowak** [comment]
hooray for more mermaid!
worth [setting shapes](https://mermaid.js.org/syntax/flowchart.html#a-node-in-a-cylindrical-shape) for S3 and ELK, and maybe kinesis to match the previous diagram?

**Comment by jonathonherbert** [comment]
Yes! [24fb938](https://github.com/guardian/editorial-tools-user-telemetry-service/pull/29/commits/24fb938097642d1d9560fd1b5d1342f4ed51b5c0)

**Review by andrew-nowak — APPROVED** [review]
Could add machine/HMAC clients on the diagram maybe to differentiate from the js lib? lgtm either way!

**Comment by jonathonherbert** [comment]
Good shout, added links to relevant auth libs above too.

**Pull request merged**
